<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Library</OutputType>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>
  <PropertyGroup>
    <Version>0.2.0-beta1</Version>
    <IsPackable>true</IsPackable>
    <PackageId>FsChat</PackageId>
    <Authors>Peter Kese</Authors>
    <Company>JSI</Company>
    <PackageDescription>FsChat: streaming LLM chat for F#</PackageDescription>
    <PackageTags>dotnet FsChat GPT AI chat</PackageTags>
    <IncludeBuildOutput>true</IncludeBuildOutput>
    <RepositoryUrl>https://github.com/pkese/FsChat</RepositoryUrl>
    <NoWarn>$(NoWarn);NU5100;VSTHRD002</NoWarn>
    <!-- dll outside of lib/ folder -->
    <!--PackageReadmeFile>../../README.md</PackageReadmeFile-->
  </PropertyGroup>
  <PropertyGroup>
    <TargetsForTfmSpecificBuildOutput>$(TargetsForTfmSpecificBuildOutput);CopyProjectReferencesToPackage</TargetsForTfmSpecificBuildOutput>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="FsChat.Types.fsx" />
    <Compile Include="FsChat.AiApi.fsx" />
    <Compile Include="FsChat.Cache.fs" />
    <Compile Include="FsChat.TableReader.fsx" />
    <Compile Include="FsChat.Markdown.fsx" />
    <Compile Include="FsChat.fsx" />
    <!--Compile Include="FsChat.CompExpr.fsx" /-->
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FSharp.Control.TaskSeq" Version="1.0.*" />
    <PackageReference Update="FSharp.Core" Version="10.1.201" />
    <PackageReference Include="FSharp.Formatting" Version="22.0.0" />
    <PackageReference Include="FSharp.SystemTextJson" Version="1.*" />
    <PackageReference Include="System.IO.Hashing" Version="10.0.6" />
    <PackageReference Include="TypeShape" Version="10.0.0" />
    <PackageReference Include="Dapper.FSharp" Version="4.10.0" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.6" />
  </ItemGroup>
  <Target DependsOnTargets="ResolveReferences" Name="CopyProjectReferencesToPackage">
    <ItemGroup>
      <BuildOutputInPackage Include="@(ReferenceCopyLocalPaths-&gt;WithMetadataValue('ReferenceSourceTarget', 'ProjectReference'))" />
    </ItemGroup>
  </Target>
</Project>